-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 18:09:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rmarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rmarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rmarket` DEFAULT CHARACTER SET utf8 ;
USE `rmarket` ;

-- -----------------------------------------------------
-- Table `rmarket`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rmarket`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`sizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `talle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rmarket`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `carrito_id` INT NULL DEFAULT NULL,
  `size_id` INT NULL DEFAULT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_sizes_idx` (`size_id` ASC) VISIBLE,
  INDEX `fk_products_carrito_idx` (`carrito_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_carrito`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `rmarket`.`carrito` (`id`),
  CONSTRAINT `fk_products_sizes`
    FOREIGN KEY (`size_id`)
    REFERENCES `rmarket`.`sizes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rmarket`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rmarket`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `address_id` INT NULL DEFAULT NULL,
  `carrito_id` INT NULL DEFAULT NULL,
  `user_type_id` INT NULL DEFAULT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_address_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_users_cart_idx` (`carrito_id` ASC) VISIBLE,
  INDEX `fk_users_type_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `rmarket`.`address` (`id`),
  CONSTRAINT `fk_users_cart`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `rmarket`.`carrito` (`id`),
  CONSTRAINT `fk_users_type`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `rmarket`.`user_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rmarket`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmarket`.`carrito` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_products_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_carrito_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_carrito_address_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `rmarket`.`address` (`id`),
  CONSTRAINT `fk_carrito_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `rmarket`.`products` (`id`),
  CONSTRAINT `fk_carrito_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `rmarket`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
